language: node_js
node_js: 
  - "10.4.1"
script:
  - npm run test
after_success: npm run coverage
services:
 - postgresql

before_script:
 - psql -c 'drop database if exists ridemyway;' -U postgres
 - psql -c 'create database ridemyway;' -U postgres
 - npm run createDb

env:
 - SECRET=thelordismyhelperishallnotwant