const SET_CURRENT_USER = 'SET_CURRENT_USER';
const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
const RIDE_CREATED = 'RIDE_CREATED';


export {
    SET_CURRENT_USER,
    ADD_FLASH_MESSAGE,
    DELETE_FLASH_MESSAGE,
    RIDE_CREATED
};